"""
KDS Reference Data — canonical code→description mappings from the
"Sales & Distribution KDS" document shared by the client.

Used by the validator to:
  1. Check that coded fields match the KDS catalog
  2. Auto-fill description fields (e.g. Inco Location from Incoterms code)
  3. Propose standardized corrections to SMEs

Last sync: 2026-04-20 (from SALES___DIST_KDS_FINAL__11032026_.xlsx)
Re-run scripts/sync_kds.py whenever the client issues a new KDS version.
"""
from __future__ import annotations

# Incoterms: code → canonical description
INCOTERMS: dict[str, str] = {
    'CFR': 'Costs and freight',
    'CIF': 'Costs Insurance and Freight',
    'CIP': 'Carriage and insurance paid to',
    'CPT': 'Carriage paid to',
    'D01': 'C and F by AIR',
    'D02': 'C and F by ROAD',
    'D03': 'C and F by SEA',
    'D04': 'CIF by AIR',
    'D05': 'CIF by SEA',
    'D06': 'CPT by AIR',
    'D07': 'CPT SAINT PETERSBURG',
    'D08': 'DAP UNICEF W/H COPENHAGEN',
    'D09': 'FCA BANGALORE by AIR',
    'D10': 'FCA CHENNAI Port Containerised',
    'D11': 'FOB BANGALORE by AIR',
    'D12': 'FOB BANGALORE by ROAD',
    'D13': 'FOB BANGALORE by SEA',
    'D14': 'FOB Cochin by SEA',
    'D15': 'DDU by AIR',
    'DAF': 'Delivered at frontier',
    'DDP': 'Delivered Duty Paid',
    'DDU': 'Delivered Duty Unpaid',
    'DEQ': 'Delivered ex quay (Duty paid)',
    'DES': 'Delivered ex ship',
    'EXW': 'Ex Works',
    'FAS': 'Free Alongside Ship',
    'FCA': 'Free Carrier',
    'FH': 'Free house',
    'FOB': 'Free on board',
    'UN': 'Not Free',
}

# Customer Group: code → description
CUSTOMER_GROUPS: dict[str, str] = {
    'DC': 'Direct Customer',
    'EM': 'Employee',
    'EX': 'Export Customer',
    'HS': 'Hospital',
    'MA': 'Major Account',
    'MD': 'Mid Account',
    'SA': 'Small Account',
    'ST': 'Stockist',
    'OC': 'One Time Customer',
    'NB': 'Non Billing Customer',
    'GV': 'Government customer',
}

# Sales Office: code → description (includes Indian states + countries)
SALES_OFFICES: dict[str, str] = {
    '01': 'Delhi',
    '02': 'NCR',
    '03': 'Andhra Pradesh',
    '04': 'Arunachal Pradesh',
    '05': 'Assam',
    '06': 'Bihar',
    '07': 'Goa',
    '08': 'Gujarat',
    '09': 'Haryana',
    '10': 'Himachal Pradesh',
    '11': 'Jammu and Kashmir',
    '12': 'Karnataka',
    '13': 'Kerala',
    '14': 'Madhya Pradesh',
    '15': 'Maharashtra',
    '16': 'Manipur',
    '17': 'Meghalaya',
    '18': 'Mizoram',
    '19': 'Nagaland',
    '20': 'Orissa',
    '21': 'Punjab',
    '22': 'Rajasthan',
    '23': 'Sikkim',
    '24': 'Tamil Nadu',
    '25': 'Tripura',
    '26': 'Uttar Pradesh',
    '27': 'West Bengal',
    '28': 'Andaman and Nico.Is.',
    '29': 'Chandigarh',
    '30': 'Dadra and Nagar Hav.',
    '31': 'Daman and Diu',
    '32': 'Lakshadweep',
    '33': 'Puducherry',
    '34': 'Chhattisgarh',
    '35': 'Jharkhand',
    '36': 'Uttarakhand (Uttaranchal)',
    '37': 'Telangana',
    '51': 'Angola',
    '52': 'Argentina',
    '53': 'Armenia',
    '54': 'Australia',
    '55': 'Austria',
    '56': 'Azerbaijan',
    '57': 'Bahrain',
    '58': 'Bangladesh',
    '59': 'Belgium',
    '60': 'Bolivia',
    '61': 'Botswana',
    '62': 'Brazil',
    '63': 'Bulgaria',
    '64': 'Burkina Faso',
    '65': 'Burundi',
    '66': 'Cambodia',
    '67': 'Chile',
    '68': 'China',
    '69': 'Colombia',
    '70': 'Côte d’Ivoire (Ivory Coast)',
    '71': 'Croatia',
    '72': 'Curaçao',
    '73': 'Cyprus',
    '74': 'Czech Republic',
    '75': 'Denmark',
    '76': 'Dominican Republic',
    '77': 'Ecuador',
    '78': 'Egypt',
    '79': 'El Salvador',
    '80': 'Ethiopia',
    '81': 'France',
    '82': 'Georgia',
    '83': 'Germany',
    '84': 'Ghana',
    '85': 'Greece',
    '86': 'Guatemala',
    '87': 'Guyana',
    '88': 'Honduras',
    '89': 'Hong Kong',
    '90': 'Hungary',
    '91': 'India',
    '92': 'Indonesia',
    '93': 'Iran',
    '94': 'Iraq',
    '95': 'Ireland',
    '96': 'Israel',
    '97': 'Italy',
    '98': 'Jordan',
    '99': 'Kazakhstan',
    '100': 'Moldova',
    '101': 'Kenya',
    '102': 'Kosovo',
    '103': 'Kuwait',
    '104': 'Kyrgyzstan',
    '105': 'Laos',
    '106': 'Lebanon',
    '107': 'Libya',
    '108': 'Lithuania',
    '109': 'Madagascar',
    '110': 'Malawi',
    '111': 'Malaysia',
    '112': 'Maldives',
    '113': 'Mali',
    '114': 'Malta',
    '115': 'Mauritius',
    '116': 'Mexico',
    '117': 'Morocco',
    '118': 'Mozambique',
    '119': 'Myanmar',
    '120': 'Namibia',
    '121': 'Nepal',
    '122': 'Netherlands',
    '123': 'New Zealand',
    '124': 'Nicaragua',
    '125': 'Nigeria',
    '126': 'Oman',
    '127': 'Panama',
    '128': 'Paraguay',
    '129': 'Peru',
    '130': 'Philippines',
    '131': 'Poland',
    '132': 'Portugal',
    '133': 'Puerto Rico',
    '134': 'Qatar',
    '135': 'Romania',
    '136': 'Russia',
    '137': 'Rwanda',
    '138': 'Saudi Arabia',
    '139': 'Serbia and Montenegro',
    '140': 'Singapore',
    '141': 'Slovakia',
    '142': 'Slovenia',
    '143': 'South Africa',
    '144': 'South Korea',
    '145': 'Spain',
    '146': 'Sri Lanka',
    '147': 'Taiwan',
    '148': 'Tanzania',
    '149': 'Thailand',
    '150': 'Togo',
    '151': 'Trinidad and Tobago',
    '152': 'Turkey',
    '153': 'Turkmenistan',
    '154': 'Uganda',
    '155': 'Ukraine',
    '156': 'United Arab Emirates',
    '157': 'United Kingdom',
    '158': 'United States',
    '159': 'Uzbekistan',
    '160': 'Venezuela',
    '161': 'Vietnam',
    '162': 'Yemen',
    '163': 'Zambia',
    '164': 'Zimbabwe',
    '165': 'Senegal',
    '166': 'Eswatini',
    '167': 'Switzerland',
    '168': 'Tunisia',
    '169': 'Miami',
    '170': 'Costa Rica',
    '171': 'Algeria',
    '172': 'Japan',
    '173': 'Swaziland',
}

# Sales Groups: code → description
SALES_GROUPS: dict[str, str] = {
    '01': 'New Delhi',
    '02': 'Noida',
    '03': 'Amaravati',
    '04': 'Itanagar',
    '05': 'Dispur',
    '06': 'Patna',
    '07': 'Panaji',
    '08': 'Gandhinagar',
    '09': 'Chandigarh',
    '10': 'Shimla',
    '11': 'Srinagar/Jammu',
    '12': 'Bengaluru',
    '13': 'Thiruvananthapuram',
    '14': 'Bhopal',
    '15': 'Mumbai',
    '16': 'Imphal',
    '17': 'Shillong',
    '18': 'Aizawl',
    '19': 'Kohima',
    '20': 'Bhubaneswar',
    '21': 'Chandigarh',
    '22': 'Jaipur',
    '23': 'Gangtok',
    '24': 'Chennai',
    '25': 'Agartala',
    '26': 'Lucknow',
    '27': 'Kolkata',
    '28': 'Port Blair',
    '29': 'Chandigarh',
    '30': 'Daman',
    '31': 'Daman',
    '32': 'Kavaratti',
    '33': 'Puducherry',
    '34': 'Raipur',
    '35': 'Ranchi',
    '36': 'Dehradun',
    '37': 'Hyderabad',
    '51': 'Luanda',
    '52': 'Buenos Aires',
    '53': 'Yerevan',
    '54': 'Canberra',
    '55': 'Vienna',
    '56': 'Baku',
    '57': 'Manama',
    '58': 'Dhaka',
    '59': 'Brussels',
    '60': 'Sucre / La Paz',
    '61': 'Gaborone',
    '62': 'Brasília',
    '63': 'Sofia',
    '64': 'Ouagadougou',
    '65': 'Gitega',
    '66': 'Phnom Penh',
    '67': 'Santiago',
    '68': 'Beijing',
    '69': 'Bogotá',
    '70': 'Yamoussoukro',
    '71': 'Zagreb',
    '72': 'Willemstad',
    '73': 'Nicosia',
    '74': 'Prague',
    '75': 'Copenhagen',
    '76': 'Santo Domingo',
    '77': 'Quito',
    '78': 'Cairo',
    '79': 'San Salvador',
    '80': 'Addis Ababa',
    '81': 'Paris',
    '82': 'Tbilisi',
    '83': 'Berlin',
    '84': 'Accra',
    '85': 'Athens',
    '86': 'Guatemala City',
    '87': 'Georgetown',
    '88': 'Tegucigalpa',
    '89': 'Hong Kong',
    '90': 'Budapest',
    '91': 'New Delhi',
    '92': 'Jakarta',
    '93': 'Tehran',
    '94': 'Baghdad',
    '95': 'Dublin',
    '96': 'Jerusalem',
    '97': 'Rome',
    '98': 'Amman',
    '99': 'Astana (Nur-Sultan)',
    '100': 'Nairobi',
    '101': 'Pristina',
    '102': 'Kuwait City',
    '103': 'Bishkek',
    '104': 'Vientiane',
    '105': 'Beirut',
    '106': 'Tripoli',
    '107': 'Vilnius',
    '108': 'Antananarivo',
    '109': 'Lilongwe',
    '110': 'Kuala Lumpur',
    '111': 'Malé',
    '112': 'Bamako',
    '113': 'Valletta',
    '114': 'Port Louis',
    '115': 'Mexico City',
    '116': 'Chișinău',
    '117': 'Rabat',
    '118': 'Maputo',
    '119': 'Naypyidaw',
    '120': 'Windhoek',
    '121': 'Kathmandu',
    '122': 'Amsterdam',
    '123': 'Wellington',
    '124': 'Managua',
    '125': 'Abuja',
    '126': 'Muscat',
    '127': 'Panama City',
    '128': 'Asunción',
    '129': 'Lima',
    '130': 'Manila',
    '131': 'Warsaw',
    '132': 'Lisbon',
    '133': 'San Juan',
    '134': 'Doha',
    '135': 'Bucharest',
    '136': 'Moscow',
    '137': 'Kigali',
    '138': 'Riyadh',
    '139': 'Belgrade / Podgorica',
    '140': 'Singapore',
    '141': 'Bratislava',
    '142': 'Ljubljana',
    '143': 'Pretoria / Cape Town / Bloemfontein',
    '144': 'Seoul',
    '145': 'Madrid',
    '146': 'Sri Jayawardenepura Kotte / Colombo',
    '147': 'Taipei',
    '148': 'Dodoma',
    '149': 'Bangkok',
    '150': 'Lomé',
    '151': 'Port of Spain',
    '152': 'Ankara',
    '153': 'Ashgabat',
    '154': 'Kampala',
    '155': 'Kyiv',
    '156': 'Abu Dhabi',
    '157': 'London',
    '158': 'Washington, D.C.',
    '159': 'Tashkent',
    '160': 'Caracas',
    '161': 'Hanoi',
    '162': 'Sana’a',
    '163': 'Lusaka',
    '164': 'Harare',
    '165': 'Dakar',
    '166': 'Mbabane',
    '201': 'ADONI',
    '202': 'AKIVEDU',
    '203': 'ALLAGADDA',
    '204': 'AMALAPURAM',
    '205': 'AMBAJIPETA',
    '206': 'ANAKAPALLI',
    '207': 'ANANTAPUR',
    '208': 'ANAPARTI',
    '209': 'ATMAKUR',
    '210': 'BHADRACHELAM',
    '211': 'BHIMAVARAM',
    '212': 'BIKKAVOLU',
    '213': 'BOBBLI',
    '214': 'CHAGALLU',
    '215': 'CHALLAPALLI',
    '216': 'CHIRALA',
    '217': 'CHILAKLURIPET',
    '218': 'CHIPURUPALLE',
    '219': 'CHITHOOR',
    '220': 'CHODAVARAM',
    '221': 'KADAPA',
    '222': 'DHARMAVARAM',
    '223': 'DHONE',
    '224': 'DRAKSHARAMAM',
    '225': 'ELURU',
    '226': 'G.MAMIDADA',
    '227': 'GAJAPATHINAGARAM',
    '228': 'GAJUWAKA',
    '229': 'GODHAVARIKHANI',
    '230': 'GUDIVADA',
    '231': 'GUDOR',
    '232': 'GUNTAKAL',
    '233': 'GUNTUR',
    '234': 'HINDUPUR',
    '235': 'ICHAPURAM',
    '236': 'JAGGAIAHPET',
    '237': 'JAGGAMPETA',
    '238': 'JAMMALAMADUGU',
    '239': 'JAMMIKUNTA',
    '240': 'JANGARADDYGUDUM',
    '241': 'KADIRI',
    '242': 'KAKINADA',
    '243': 'KALLURU',
    '244': 'KALYANDURGAM',
    '245': 'KANDUKUR',
    '246': 'KATHIPUDI',
    '247': 'KAVALI',
    '248': 'KOTHAPETA',
    '249': 'KOTHAVALASA',
    '250': 'KUPPAM',
    '251': 'KURNOOL',
    '252': 'MACHARLA',
    '253': 'MACHILIPATNAM',
    '254': 'MADANAPALLY',
    '255': 'MADHURAWADA',
    '256': 'MADUGULA',
    '257': 'MALIKIPURAM',
    '258': 'MANDAPET',
    '259': 'MANGALAGIRI',
    '260': 'MARKAPUR',
    '261': 'MUMMIDIVARAM',
    '262': 'MYDUKUR',
    '263': 'MYLAVARAM',
    '264': 'NAGARKURNOOL',
    '265': 'NAIDUPET',
    '266': 'NANDIGAMA',
    '267': 'NANDYAL',
    '268': 'NARASANNAPET',
    '269': 'NARASAPURAM',
    '270': 'NARASARAOPET',
    '271': 'NARSIPATNAM',
    '272': 'NELLIMARLA',
    '273': 'NELLORE',
    '274': 'NIDADAVOLE',
    '275': 'NUZVEDU',
    '276': 'ONGOLE',
    '277': 'PALAKOLLU',
    '278': 'PALAMANER',
    '279': 'PALASA',
    '280': 'PARVATHIPURAM',
    '281': 'PEDDAPURAM',
    '282': 'PIDUGURALLA',
    '283': 'PILERU',
    '284': 'PITHAPURAM',
    '285': 'PONNUR',
    '286': 'PORUMAMILLA',
    '287': 'PRODDATUR',
    '288': 'PULIVENDULA',
    '289': 'PUNDI',
    '290': 'PUTTAPARTHI',
    '291': 'RAILWAY KODURU',
    '292': 'RAJAHMUNDHRY',
    '293': 'RAJAM',
    '294': 'RAJAMPET',
    '295': 'RAJANAGARAM',
    '296': 'RAMACHANDRA PURAM',
    '297': 'RAVULAPALEM',
    '298': 'RAYACHOTI',
    '299': 'RAYAVARAM',
    '300': 'RAZOLE',
    '301': 'REPALLI',
    '302': 'SALUR',
    '303': 'SAMALKOTA',
    '304': 'SATTENPALLI',
    '305': 'SINGARAYAKONDA',
    '306': 'SOMPETA',
    '307': 'SRIHARIKOTA',
    '308': 'SRIKAKULAM',
    '309': 'SRIKALAHASTHI',
    '310': 'SRUNGAVARUPAKOTA',
    '311': 'SULLURPETA',
    '312': 'TADEPALLIGUDUM',
    '313': 'TADIPATHRI',
    '314': 'TANUKU',
    '315': 'TATIPAKA',
    '316': 'TENALI',
    '317': 'THAGARAPUVALASA',
    '318': 'TIRUPATI',
    '319': 'TIRUVURU',
    '320': 'TUNI',
    '321': 'UDAYAGIRI',
    '322': 'VENKATGIRI',
    '323': 'VIJAYAWADA',
    '324': 'VINJUMUR',
    '325': 'VINUKUNDA',
    '326': 'VISAKHAPATNAM',
    '327': 'VIZIANAGARAM',
    '328': 'VUYYUR',
    '329': 'WESTGODAVARI',
    '330': 'YELESWARAM',
    '331': 'ITANAGAR',
    '332': 'NAHARLAGUN',
    '333': 'PASIGHAT',
    '334': 'TEZU',
    '335': 'AMINGAON',
    '336': 'BARPETA',
    '337': 'BIJNI',
    '338': 'BONGAIGAON',
    '339': 'BONKONG',
    '340': 'CHABUA',
    '341': 'DHUBURI',
    '342': 'DIBRUGARH',
    '343': 'DIGBOI',
    '344': 'DISPUR',
    '345': 'DOOMDOOMA',
    '346': 'DULIAJAN',
    '347': 'GOALPARA',
    '348': 'GOLAGHAT',
    '349': 'GUWAHATI',
    '350': 'HOJAI',
    '351': 'JORHAT',
    '352': 'KOKRAJHAR',
    '353': 'LAKHIPUR',
    '354': 'MAKUNDA',
    '355': 'MANGALDAI',
    '356': 'MARGERITA',
    '357': 'MORIGAON',
    '358': 'NAGAON',
    '359': 'NALBARI',
    '360': 'NORTH LAKHIMPUR',
    '361': 'PAILAPOOL',
    '362': 'PALASBARI',
    '363': 'PATHSALA',
    '364': 'RANGIA',
    '365': 'SIVASAGAR',
    '366': 'SILCHAR',
    '367': 'TEZPUR',
    '368': 'TINSUKIA',
    '369': 'AMARPUR',
    '370': 'ARARIYA',
    '371': 'ARERAJ',
    '372': 'ARRAH',
    '373': 'AURANGABAD(BIHAR)',
    '374': 'BAGHA',
    '375': 'BAHERI',
    '376': 'BAKHTIYARPUR',
    '377': 'BALMIKI NAGAR',
    '378': 'BANKA',
    '379': 'BARH',
    '380': 'BEGUSARAI',
    '381': 'BENIPATHI',
    '382': 'BETTIAH',
    '383': 'BHAGALPUR',
    '384': 'BIHAR SHARIF',
    '385': 'BIHTA',
    '386': 'BUXAR',
    '387': 'CHAKIA',
    '388': 'CHAPRA',
    '389': 'DALSING SARAI',
    '390': 'DANAPUR',
    '391': 'DARBHANGA',
    '392': 'DAUDNAGAR',
    '393': 'DEHRI-ON-SON',
    '394': 'DHAKA(BIHAR)',
    '395': 'EKMA',
    '396': 'FATUHA',
    '397': 'FORBISGANJ',
    '398': 'GAYA',
    '399': 'GOPALGANJ',
    '400': 'HAJIPUR',
    '401': 'HARNATAND',
    '402': 'JAMUI',
    '403': 'JANDHA',
    '404': 'JAYNAGAR',
    '405': 'JEHANABAD',
    '406': 'JHA JHA',
    '407': 'JHANJHARPUR',
    '408': 'JHARIA',
    '409': 'KAHALGAON',
    '410': 'KATIHAR',
    '411': 'KESARIYA',
    '412': 'KHAGARIA',
    '413': 'KHERWA',
    '414': 'KISHANGANJ',
    '415': 'KOTWA',
    '416': 'KUSHESHWAR ASTHAN',
    '417': 'LAKHISARAI',
    '418': 'MADHEPUR',
    '419': 'MADHUBANI',
    '420': 'MAHUA',
    '421': 'MAJORGANJ',
    '422': 'MIRGANJ',
    '423': 'MOTIHARI',
    '424': 'MOTIPUR',
    '425': 'MUNGER',
    '426': 'MUZZAFARPUR',
    '427': 'NARKATIAGANJ',
    '428': 'NAWADA',
    '429': 'PATNA',
    '430': 'PHULWARI SHARIF',
    '431': 'PUPRI',
    '432': 'PURNEA',
    '433': 'PUSA',
    '434': 'RAXAUL',
    '435': 'ROHTAS',
    '436': 'ROSHRA',
    '437': 'RUNI',
    '438': 'SAHIBGANJ',
    '439': 'SAHARSA',
    '440': 'SAMASTIPUR',
    '441': 'SASARAM',
    '442': 'SITAMARHI',
    '443': 'SIWAN',
    '444': 'SONEPUR-BIHAR',
    '445': 'SUGAULI',
    '446': 'SULTANGANJ',
    '447': 'SUPAUL',
    '448': 'TURKAULIA',
    '449': 'VAISHALI',
    '450': 'ABHANPUR',
    '451': 'AMBIKAPUR',
    '452': 'BACHELI',
    '453': 'BHATAPARA',
    '454': 'BHILAI',
    '455': 'BILASPUR',
    '456': 'CHAMPA',
    '457': 'DALLIRAJHARA',
    '458': 'DHAMTARI',
    '459': 'DURG',
    '460': 'JAGADALPUR',
    '461': 'JANJGIR',
    '462': 'JASHPUR',
    '463': 'KANKER',
    '464': 'KAWARDHA',
    '465': 'KORBA',
    '466': 'MAHASAMUND',
    '467': 'MAHENDRAGARH',
    '468': 'MULUND',
    '469': 'MUNGELI',
    '470': 'RAIGARH',
    '471': 'RAIPUR',
    '472': 'RAJIM',
    '473': 'RAJNANDGAON',
    '474': 'TILDA NEWRA',
    '475': 'DELHI',
    '476': 'EAST DELHI',
    '477': 'GREATER NOIDA',
    '478': 'HODAL',
    '479': 'NORTH DELHI',
    '480': 'SAKET',
    '481': 'SOUTH DELHI',
    '482': 'WEST DELHI',
    '483': 'CANDOLIM',
    '484': 'GOA',
    '485': 'MAPUSA',
    '486': 'MARGAON',
    '487': 'MIRAMAR',
    '488': 'PANJIM',
    '489': 'PONDA',
    '490': 'PORVORIM',
    '491': 'SAQLIM',
    '492': 'VASCO',
    '493': 'AHMEDABAD',
    '494': 'AMRELI',
    '495': 'ANAND',
    '496': 'ANJAR',
    '497': 'ANKLESHWAR',
    '498': 'BALASINORE',
    '499': 'BARDOLI',
    '500': 'BARODA',
    '501': 'BAYAD',
    '502': 'BHARUCH',
    '503': 'BHAVNAGAR',
    '504': 'BHILAD',
    '505': 'BHUJ',
    '506': 'BILIMORA',
    '507': 'BODELI',
    '508': 'BORSAD',
    '509': 'BOTAD',
    '510': 'CHHOTA UDAIPUR',
    '511': 'CHIKHLI',
    '512': 'CHOTILA',
    '513': 'DABHOI',
    '514': 'DAHOD',
    '515': 'DAKOR',
    '516': 'DEESA',
    '517': 'DEHGAM',
    '518': 'DHANERA',
    '519': 'DHARAMPUR (GUJARAT)',
    '520': 'DHOLKA',
    '521': 'DHORAJI',
    '522': 'DWARKA',
    '523': 'GANDHIDHAM',
    '524': 'GANDHINAGAR',
    '525': 'GODHRA',
    '526': 'GOJARIA',
    '527': 'GONDAL',
    '528': 'HALOL',
    '529': 'HIMATNAGAR',
    '530': 'IDAR',
    '531': 'ISANPUR',
    '532': 'JAMBUSAR',
    '533': 'JAMNAGAR',
    '534': 'JETPUR',
    '535': 'JUNAGARH',
    '536': 'KADI',
    '537': 'KADODARA',
    '538': 'KALOL',
    '539': 'KAMRAJ',
    '540': 'KAPADVANJ',
    '541': 'KARAMSAD',
    '542': 'KATARGAM',
    '543': 'KATHLAL',
    '544': 'KESHOD',
    '545': 'KHAMBALIA',
    '546': 'KHAMBHAT',
    '547': 'KHEDA',
    '548': 'KHERALU',
    '549': 'KIM-KOSAMBA',
    '550': 'LUNWAD',
    '551': 'MAHUVA',
    '552': 'MANDVI',
    '553': 'MANSA-GUJ',
    '554': 'MEHSANA',
    '555': 'MODASA',
    '556': 'MORBI',
    '557': 'NADIAD',
    '558': 'NAVSARI',
    '559': 'PALANPUR',
    '560': 'PALITANA',
    '561': 'PARVATPATIA',
    '562': 'PATAN',
    '563': 'PETLAD',
    '564': 'PORBANDAR',
    '565': 'RADHANPUR',
    '566': 'RAJKOT',
    '567': 'RAJPIPLA',
    '568': 'SANAND',
    '569': 'SANTRAMPUR',
    '570': 'SATLASANA',
    '571': 'SELVAS',
    '572': 'SIDHPUR',
    '573': 'SURAT',
    '574': 'SURENDRANAGAR',
    '575': 'TARAPUR-GUJARAT',
    '576': 'THARAD',
    '577': 'UDHANA',
    '578': 'UMRETH',
    '579': 'UNA(GUJARAT)',
    '580': 'UNJHA',
    '581': 'UPLETA',
    '582': 'VADNAGAR',
    '583': 'VALSAD',
    '584': 'VANSDA',
    '585': 'VAPI',
    '586': 'VATRAK',
    '587': 'VERAVAL',
    '588': 'VIJAPUR',
    '589': 'VIRMGAM',
    '590': 'VISNAGAR',
    '591': 'VYARA',
    '592': 'WAGHODIA',
    '593': 'WANKANER',
    '594': 'AMBALA',
    '595': 'AMBALA CANTT',
    '596': 'BAHADURGARH',
    '597': 'BALABHGARH',
    '598': 'BHIWANI',
    '599': 'FARIDABAD',
    '600': 'FATEHABAD',
    '601': 'GURGAON',
    '602': 'HANSI',
    '603': 'HISAR',
    '604': 'JAGADHARI',
    '605': 'JHAJJAR',
    '606': 'JIND',
    '607': 'KAITHAL',
    '608': 'KARNAL',
    '609': 'KURUKSHETRA',
    '610': 'MAHENDARGARH',
    '611': 'MEWAT',
    '612': 'NARNAUL',
    '613': 'PALWAL',
    '614': 'PANCHKULA',
    '615': 'PANIPAT',
    '616': 'REWARI',
    '617': 'ROHTAK',
    '618': 'SIRSA',
    '619': 'SOHNA',
    '620': 'SONEPAT',
    '621': 'TOHANA',
    '622': 'YAMUNA NAGAR',
    '623': 'ANANDPUR-HIMACHAL PRADESH',
    '624': 'BILASPUR-HIMACHAL PRADESH',
    '625': 'GHUMARWIN',
    '626': 'HAMIRPUR',
    '627': 'KALKA',
    '628': 'KANGRA-HIMACHAL PRADESH',
    '629': 'KULLU',
    '630': 'MANDI',
    '631': 'NAHAN',
    '632': 'NALAGARH',
    '633': 'PALAMPUR',
    '634': 'SHIMLA',
    '635': 'SIRMAUR',
    '636': 'SOLAN',
    '637': 'UNA',
    '638': 'AKHNOOR',
    '639': 'ANANTNAG',
    '640': 'BARAMULLA',
    '641': 'DODA',
    '642': 'JAMMU',
    '643': 'KATHUA J&K',
    '644': 'KATRA',
    '645': 'RAJOURI',
    '646': 'SAMBA',
    '647': 'SRINAGAR',
    '648': 'UDHAMPUR',
    '649': 'BOKARO',
    '650': 'CHAIBASA',
    '651': 'CHANDRAPURA',
    '652': 'CHIRKUNDA',
    '653': 'DALTENGANJ',
    '654': 'DEOGHAR',
    '655': 'DHANBAD',
    '656': 'DUMKA-JHARKHAND',
    '657': 'GARWAH',
    '658': 'GHATO',
    '659': 'GHATSHILA',
    '660': 'GIRIDIH',
    '661': 'GODDA',
    '662': 'GUMLA',
    '663': 'HAZARIBAGH',
    '664': 'JAMADOBA',
    '665': 'JAMESHEDPUR',
    '666': 'JAMTARA',
    '667': 'KATRAS',
    '668': 'KHUNTI',
    '669': 'KODARMA',
    '670': 'LOHARDAGA',
    '671': 'MADHUPUR',
    '672': 'MANDAR',
    '673': 'NIRSA',
    '674': 'PAKUR',
    '675': 'RAMGHAR',
    '676': 'RANCHI',
    '677': 'ANEKAL',
    '678': 'ANKOLA',
    '679': 'ARSIKERE',
    '680': 'ATHANI',
    '681': 'BADAMI',
    '682': 'BAGALKOT',
    '683': 'BAILHONGAL',
    '684': 'BANGALORE',
    '685': 'BANGARAPET',
    '686': 'BANTWAL',
    '687': 'BASAVAKALYAN',
    '688': 'BELGAUM',
    '689': 'BELLARY',
    '690': 'BELLUR',
    '691': 'BELTHANGADY',
    '692': 'BHADRAVATI',
    '693': 'BHALKI',
    '694': 'BHATKAL',
    '695': 'BIDAR',
    '696': 'BIJAPUR',
    '697': 'BIRUR',
    '698': 'CHALLAKERE',
    '699': 'CHAMRAJNAGAR',
    '700': 'CHANNARAYAPATNA',
    '701': 'CHENNAPATNA',
    '702': 'CHIKKABALAPUR',
    '703': 'CHIKKAMAGALUR',
    '704': 'CHIKODI',
    '705': 'CHINTHAMANI',
    '706': 'CHITRADURGA',
    '707': 'DANDELI',
    '708': 'DAVANAGERE',
    '709': 'DEVANAHALLI',
    '710': 'DHARWAD',
    '711': 'DODDABALAPUR',
    '712': 'GADAG',
    '713': 'GANGAVATHI',
    '714': 'GATAPRABA',
    '715': 'GAURIBIDANUR',
    '716': 'GOKAK',
    '717': 'GONIKOPPA',
    '718': 'GULBARGA',
    '719': 'H B HALLI',
    '720': 'HARUGERI',
    '721': 'HASSAN',
    '722': 'HAVERI',
    '723': 'HIRIUR',
    '724': 'HERPNALLI',
    '725': 'HONAVAR',
    '726': 'HOSDURGA',
    '727': 'HOSKOTE',
    '728': 'HOSPET',
    '729': 'HUBLI',
    '730': 'ILKAL',
    '731': 'INDI',
    '732': 'JAMKANDHI',
    '733': 'K.G.F',
    '734': 'K.R.NAGAR',
    '735': 'KADUR',
    '736': 'KALASA',
    '737': 'KARKALA',
    '738': 'KARWAR',
    '739': 'KENGERI',
    '740': 'KOLAR',
    '741': 'KOLLEGAL',
    '742': 'KOPPA',
    '743': 'KOPPAL',
    '744': 'KORATAGERI',
    '745': 'KUMTA',
    '746': 'KUNDAPUR',
    '747': 'KUNIGAL',
    '748': 'LINGSUGUR',
    '749': 'MADIKERE',
    '750': 'MAHALINGPUR',
    '751': 'MANAVI',
    '752': 'MANDYA',
    '753': 'MANGALORE',
    '754': 'MANIPAL',
    '755': 'MOODABIDRI',
    '756': 'MUDDEBIHAL',
    '757': 'MUDHOL',
    '758': 'MYSORE',
    '759': 'NARASIMHARAJAPURA',
    '760': 'NELAMANGALA',
    '761': 'NIPANI',
    '762': 'PAVAGADA',
    '763': 'PUTTUR',
    '764': 'RABKAVI',
    '765': 'RAICHUR',
    '766': 'RAMANAGAR',
    '767': 'RAMDURG',
    '768': 'RANEBENUR',
    '769': 'SANKESHWAR',
    '770': 'SAUNDATTI',
    '771': 'SHAHAPUR',
    '772': 'SHIMOGA',
    '773': 'SINDAGI',
    '774': 'SINDHANOOR',
    '775': 'SIRA',
    '776': 'SIRSI',
    '777': 'SIRUGUPPA',
    '778': 'SRINIVASPUR',
    '779': 'SULLIA',
    '780': 'TALIKOTI',
    '781': 'TARIKERE',
    '782': 'THIRTHAHALLI',
    '783': 'TIPTUR',
    '784': 'TORANAGALLU',
    '785': 'TUMKUR',
    '786': 'TURVEKERE',
    '787': 'UDUPI',
    '788': 'UJIRE',
    '789': 'ULLAL',
    '790': 'YADGIR',
    '791': 'ADOOR',
    '792': 'ALWAYE',
    '793': 'ATTINGAL',
    '794': 'BATHERY',
    '795': 'CALICUT',
    '796': 'KANNUR',
    '797': 'CHALAKKUDY',
    '798': 'CHANGANASERRY',
    '799': 'CHEMMAD',
    '800': 'CHENGANNOOR',
    '801': 'CHOONDAL',
    '802': 'COCHIN',
    '803': 'EDAPPAL',
    '804': 'ETTUMANOOR',
    '805': 'FEROKE',
    '806': 'IRINJALAKKUDA',
    '807': 'KANJIRAPPALLY',
    '808': 'KASARGOD',
    '809': 'KAYAMKULAM',
    '810': 'KODAKARA',
    '811': 'KODUNGALLUR',
    '812': 'KOLLAM',
    '813': 'KONDOTTY',
    '814': 'KOOTHATTUKULAM',
    '815': 'KORATTY',
    '816': 'KOTTAKKAL',
    '817': 'KOTTAYAM',
    '818': 'KOTTIYAM',
    '819': 'KOZHENCHERRY',
    '820': 'KUNNAMKULAM',
    '821': 'MALAPURAM',
    '822': 'MANANTHAVADY',
    '823': 'MANJERI',
    '824': 'MAVELIKKARA',
    '825': 'MUKKAM',
    '826': 'NILAMBUR',
    '827': 'PALAI',
    '828': 'PALAKKAD',
    '829': 'PANDIKKAD',
    '830': 'PANTHALAM',
    '831': 'PARUMALA',
    '832': 'PATHANAMTHITTA',
    '833': 'PATTAMBI',
    '834': 'PERINTHELMANNA',
    '835': 'PERUMBAVOOR',
    '836': 'PERUMPILAVU',
    '837': 'PONNANI',
    '838': 'THAMARASSERY',
    '839': 'THIRUVALLA',
    '840': 'TRIVANDRUM',
    '841': 'THODUPUZHA',
    '842': 'THRISSUR',
    '843': 'TIRUR',
    '844': 'TIRUVALLA',
    '845': 'TRIPUNITHURA',
    '846': 'VADAKARA',
    '847': 'VADAKKENCHERY',
    '848': 'VAIKOM',
    '849': 'VALANCHERY',
    '850': 'VANDOOR',
    '851': 'ASHOK NAGAR',
    '852': 'BADNAGAR',
    '853': 'BARWANI',
    '854': 'BALAGHAT',
    '855': 'BARWAH',
    '856': 'BETUL',
    '857': 'BHIND',
    '858': 'BHOPAL',
    '859': 'BURHANPUR',
    '860': 'CHHATARPUR',
    '861': 'CHINDWARA',
    '862': 'CHITRAKOOT-MP',
    '863': 'DAMOH',
    '864': 'DATIA',
    '865': 'DEWAS',
    '866': 'DHAMNOD',
    '867': 'DHAR',
    '868': 'GUNA',
    '869': 'GWALIOR',
    '870': 'HARDA',
    '871': 'HATPIPLIYA',
    '872': 'HOSHANGABAD',
    '873': 'INDORE',
    '874': 'ITRASI',
    '875': 'JABALPUR',
    '876': 'KATNI',
    '877': 'KHANDWA',
    '878': 'KHARGONE',
    '879': 'MANDSOUR',
    '880': 'MHOW',
    '881': 'MORENA',
    '882': 'NAGDA',
    '883': 'NARSINGHPUR',
    '884': 'NEEMUCH',
    '885': 'PANNA',
    '886': 'RAJGARH(MP)',
    '887': 'RATLAM',
    '888': 'REWA',
    '889': 'SAGAR',
    '890': 'SHAJAPUR',
    '891': 'SANAWAD',
    '892': 'SATNA',
    '893': 'SEHORE',
    '894': 'SEONI',
    '895': 'SHAHDOL',
    '896': 'SHIVPURI',
    '897': 'SIDHI',
    '898': 'SINGRAULI',
    '899': 'THANDLA',
    '900': 'TIKAMGARH',
    '901': 'UJJAIN',
    '902': 'VIDISHA',
    '903': 'AHMEDNAGAR',
    '904': 'AHMEDPUR',
    '905': 'AIROLI',
    '906': 'AKLUJ',
    '907': 'AKOLA',
    '908': 'AKOT',
    '909': 'ALANDI',
    '910': 'ALIBAG',
    '911': 'AMALNER',
    '912': 'AMBAJOGAI',
    '913': 'AMRAVATI',
    '914': 'ANDHERI',
    '915': 'AURANGABAD',
    '916': 'BANDRA',
    '917': 'BARAMATI',
    '918': 'BARSHI',
    '919': 'BEED',
    '920': 'BHANDARA',
    '921': 'BHAYANDAR',
    '922': 'BHIWANDI',
    '923': 'BHOR',
    '924': 'BHOSARI',
    '925': 'BHULDANA',
    '926': 'BHUSAWAL',
    '927': 'BOISAR',
    '928': 'BORIVALI',
    '929': 'BRAHMAPURI',
    '930': 'BULDHANA',
    '931': 'BYCULLA',
    '932': 'CHAKAN',
    '933': 'CHALISGAON',
    '934': 'CHANDRAPUR',
    '935': 'CHARNI ROAD',
    '936': 'CHEMBUR',
    '937': 'CHIKHLI-MAHARASHTRA',
    '938': 'CHINCHWAD',
    '939': 'CHIPLUN',
    '940': 'CHOPDA',
    '941': 'DADAR',
    '942': 'DAHANU',
    '943': 'DAHISAR-MUMBAI',
    '944': 'DAUND',
    '945': 'DEGLUR',
    '946': 'DEHU',
    '947': 'DHULE',
    '948': 'DHULIA',
    '949': 'DINDORI',
    '950': 'DOMBIVILI',
    '951': 'GADCHIROLI',
    '952': 'GANGAPUR',
    '953': 'GHATKOPAR',
    '954': 'GHODEGAON',
    '955': 'GONDIA',
    '956': 'GOREGAON',
    '957': 'HADAPSAR',
    '958': 'HINGOLI',
    '959': 'ICHALKARANJI',
    '960': 'INDAPUR',
    '961': 'ISLAMPUR(MAH)',
    '962': 'JALGAON',
    '963': 'JALNA',
    '964': 'JAMKHED',
    '965': 'JATT',
    '966': 'JAYSINGHPUR',
    '967': 'JOGESHWARI',
    '968': 'KALYAN',
    '969': 'KANDIVALI',
    '970': 'KANKAKWALI',
    '971': 'KARAD',
    '972': 'KARJAT',
    '973': 'KASHTI',
    '974': 'KHAMGAON',
    '975': 'KHAR ROAD',
    '976': 'KHARGHAR-MUMBAI',
    '977': 'KHED',
    '978': 'KHOPOLI',
    '979': 'KINWAT',
    '980': 'KOLHAPUR',
    '981': 'KOPAR KHAIRANE-MUMBAI',
    '982': 'KOPARGAON',
    '983': 'KUDAL',
    '984': 'KURLA',
    '985': 'LATUR',
    '986': 'LONAND',
    '987': 'LONAVALA',
    '988': 'MAHIM',
    '989': 'MALAD',
    '990': 'MALEGAON',
    '991': 'MALKAPUR',
    '992': 'MANGAON',
    '993': 'MANMAD',
    '994': 'MASJID BANDAR',
    '995': 'MATUNGA',
    '996': 'MAZGAON',
    '997': 'MEHKAR',
    '998': 'MIRA ROAD',
    '999': 'MIRAJ',
}

# Division: code → description
DIVISIONS: dict[str, str] = {
    '01': 'Surgicals',
    '02': 'Consumex',
    '03': 'Endoscopy',
    '04': 'Arthoscopy',
    '05': 'Hemostat (Abgel)',
    '06': 'AWC (CareNow)',
    '07': 'Infection Prevention (IPP)',
    '08': 'Needles',
    '09': 'Wound closure',
    '10': 'Machine and tools',
    '21': 'Miscellaneous',
    '22': 'Subcontracting',
    '00': 'Common Division',
    '21': 'Miscellaneous',
    '23': 'Medical Devices - Staplers and Ligation',
    '24': 'Medical Devices - Others',
    '08': 'Needles',
    '21': 'Miscellaneous',
    '23': 'Medical Devices - Staplers and Ligation',
    '24': 'Medical Devices - Others',
    '07': 'Infection Prevention (IPP)',
    '06': 'AWC (CareNow)',
    '91': 'Surgicals - Q-Close Sale',
    '04': 'Arthoscopy',
}

# Distribution Channel: code → description
DISTRIBUTION_CHANNELS: dict[str, str] = {
    '10': 'Direct Sales(D)',
    '15': 'Key Account',
    '20': 'Tender Domestic Business',
    '30': 'IB-Tender',
    '31': 'IB- Branded',
    '32': 'IB - Others',
    '33': 'IB OEM',
    '40': 'Stock Transfer',
    '50': 'Corporate',
    '60': 'Intercompany Sales',
    '70': 'FI Sales',
    '80': 'Scrap Sales',
    '51': 'Needle Domestic Sales',
    '52': 'Needle Export Sales',
    '51': 'Needle Domestic Sales',
    '52': 'Needle Export Sales',
    '10': 'Direct Sales(D)',
    '15': 'Key Account',
    '20': 'Tender Domestic Business',
    '30': 'IB-Tender',
    '31': 'IB- Branded',
    '32': 'IB - Others',
    '33': 'IB OEM',
    '40': 'Stock Transfer',
    '50': 'Corporate',
    '60': 'Intercompany Sales',
    '70': 'FI Sales',
    '80': 'Scrap Sales',
    '91': 'UK Domestic',
    '92': 'UK International',
    '93': 'Q-Close Sale',
    '94': 'Arthroscopy Q-close',
}

# Sales Organization: code → (name, description)
SALES_ORGS: dict[str, str] = {
    'Sales Org. Code': 'Description',
    'IN02': 'HML Sales Organization',
    'IN03': 'QNPM Sales Org.',
    'IN04': 'CareNow Medical Pvt',
    'IN05': 'CareNow Lifesciences',
    'UK02': 'Healthium Medtech UK',
}

# Sales District: code → description
SALES_DISTRICTS: dict[str, str] = {
    '000001': 'Northern region Ind',
    '000002': 'Southern region Ind',
    '000003': 'Eastern region Ind',
    '000004': 'Western region Ind',
    '000005': 'Europe & UK region',
    '000006': 'South Asia region',
    '000007': 'South East Asia regi',
    '000008': 'North Asian region',
    '000009': 'Central America regi',
    '000010': 'South America region',
    '000011': 'North America region',
    '000012': 'Africa region',
    '000013': 'Middle East region',
    '000014': 'Aus&New Zealand regi',
    '000015': 'Central Asia',
    '000016': 'East Asia Region',
    'North': 'Northern region of Indian market',
    'East': 'Eastern region of Indian market',
    'South': 'Southern region of Indian market',
    'West': 'Western region of Indian market',
    'Europe': 'Customers located in Europe and UK countries',
    'South Asia': 'Customers in South Asian countries except India',
    'South East Asia': 'Customers in South East Asian countries',
    'North Asia': 'Customers in North Asian countries',
    'Central America': 'Customers in Central America',
    'South America': 'Customers in South America',
    'North America': 'Customers in USA and Canada',
    'Africa': 'Customers across African countries',
    'Middle East': 'Customers in Middle Eastern countries',
    'ANZ': 'Customers of Australia and New Zealand',
}

# Shipping Conditions: code → description
SHIPPING_CONDITIONS: dict[str, str] = {
    '1': 'Standard Shipping Condition',
    '2': 'Pick up',
    '3': 'Express shipping',
}


# ─── Rule → catalog mapping ───────────────────────────────────────────
# Loaded from the client's real KDS xlsx at import time. The xlsx lives in
# `backend/kds/Sales_and_Dist_KDS.xlsx` and can be replaced by an admin
# on-box without a redeploy (service restart will pick up the new file).
# If the file is missing or malformed, we fall back to the hardcoded
# dicts defined above so validation still works — just with stale data.
#
# KDS-in-DB (v32) will replace this with a proper database-backed catalog
# and admin upload UI. For now this is the honest middle ground.

from pathlib import Path as _Path
from . import kds_loader as _kds_loader

_KDS_XLSX_PATH = _Path(__file__).parent.parent / "kds" / "Sales_and_Dist_KDS.xlsx"

# Start with hardcoded fallback, then overlay with what we can load from xlsx
CATALOG_BY_RULE: dict[str, dict[str, str]] = {
    "inco_location_description":  INCOTERMS,
    "sales_office_not_in_kds":    SALES_OFFICES,
    "customer_group_not_in_kds":  CUSTOMER_GROUPS,
    "division_not_in_kds":        DIVISIONS,
    "distribution_channel_not_in_kds": DISTRIBUTION_CHANNELS,
    "sales_org_not_in_kds":       SALES_ORGS,
    "sales_district_not_in_kds":  SALES_DISTRICTS,
    "shipping_condition_not_in_kds": SHIPPING_CONDITIONS,
    # Sales Groups intentionally not in the hardcoded fallback — the
    # hardcoded SALES_GROUPS was misaligned with the real client KDS
    # (contained Guatemala City etc.) and caused wrong suggestions.
    # If the xlsx load below fails, this rule simply gets no catalog
    # (empty dict → no suggestions, which is correct for now).
}

if _KDS_XLSX_PATH.exists():
    try:
        _loaded = _kds_loader.load_catalogs(_KDS_XLSX_PATH)
        # Only overlay catalogs that actually loaded non-empty; keep the
        # hardcoded fallback for any that failed.
        for _rule, _cat in _loaded.items():
            if _cat:
                CATALOG_BY_RULE[_rule] = _cat
        print(f"[kds_reference] loaded {len(_loaded)} catalogs from "
              f"{_KDS_XLSX_PATH.name} ({sum(len(c) for c in _loaded.values())} total entries)",
              flush=True)
    except Exception as _e:
        print(f"[kds_reference] WARN: could not load KDS xlsx: {_e} — using hardcoded fallback",
              flush=True)
else:
    print(f"[kds_reference] NOTE: no KDS xlsx at {_KDS_XLSX_PATH} — using hardcoded catalogs",
          flush=True)


def closest_matches(bad_value: str, catalog: dict[str, str],
                    top_n: int = 3, min_ratio: float = 0.65) -> list[dict]:
    """Return the top_n closest-matching catalog entries for a bad value.

    Uses difflib.SequenceMatcher (stdlib — no extra dependency needed on
    the Windows VM). Matches against BOTH the code and the description,
    so 'DELHI' finds '07' (description 'Delhi') and 'sales_grp_01' finds
    '01' (description 'New Delhi').

    min_ratio default of 0.65 empirically rejects nonsense matches like
    'NA' → '91 India' (ratio 0.57) while still catching typos like
    'karnatka' → 'Karnataka' (ratio 0.94). Tune per-caller if needed.

    Returns: [{"code": "01", "description": "New Delhi", "ratio": 0.82}, ...]
    """
    import difflib
    if not bad_value or not catalog:
        return []
    bad_lower = bad_value.strip().casefold()
    scored: list[tuple[float, str, str]] = []
    for code, desc in catalog.items():
        # Score against whichever (code or description) gives the better ratio.
        # SMEs might type either "07" or "Delhi"; both should find the same row.
        code_ratio = difflib.SequenceMatcher(None, bad_lower, code.casefold()).ratio()
        desc_ratio = difflib.SequenceMatcher(None, bad_lower, (desc or "").casefold()).ratio()
        ratio = max(code_ratio, desc_ratio)
        if ratio >= min_ratio:
            scored.append((ratio, code, desc or ""))
    scored.sort(reverse=True)
    return [{"code": c, "description": d, "ratio": round(r, 2)}
            for r, c, d in scored[:top_n]]
